### ISSUE TITLE
E-Series Firmware download link should point to new "StorageGrid Appliance Firmware" download site

### ISSUE THREAD

**Issue by siegfried-h** [NetAppDocs/storagegrid-116#4] opened 2022-04-01 15:19 UTC
Page: [Upgrade SANtricity OS on storage controllers](https://docs.netapp.com/us-en/storagegrid-116/sg6000/upgrading-santricity-os-on-storage-controllers.html)

The Download link for the E-Series Firmware should point to the new storagegrid appliance firmware download site and not the E-Series download site:

currectly pointing to;
[NetApp Downloads: SANtricity OS](https://mysupport.netapp.com/site/products/all/details/eseries-santricityos/downloads-tab)

should point to:
https://mysupport.netapp.com/site/products/all/details/storagegrid-appliance/downloads-tab

regards
Siegfried

**Comment by netapp-madkat** [comment] 2022-05-05 15:41
Thank you, @siegfried-h. Sorry that I missed this issue previously (I saw the other one you submitted). We've updated all affected links in the 11.6 doc site, but we are waiting for a couple of other fixes to be complete before merging the changes. 

Thanks again,

Kathy

**Comment by netapp-madkat** [comment] 2022-05-05 18:08
ah, my mistake. This issue is slightly different than what you reported in the other one (https://github.com/NetAppDocs/storagegrid-116/issues/5). In this case, the link incorrectly goes to the E-series download page instead of to the StorageGRID Appliance page. I'll will fix this one as well.

**Comment by netapp-madkat** [comment] 2022-05-05 18:18
@siegfried-h: You did everything right! I wasn't initially watching for activity on our new repo, so I missed it. And then I misread your 2nd reported issue as a duplicate of the first. I just realized that it is related, but not the same. 

Please keep reporting things here as you find them.  We really appreciate it.

Thanks,

Kathy

**Comment by netapp-madkat** [comment] 2022-05-17 20:41
Hi Siegfried, 

We have now updated the 11.6 doc site and we added links to the new StorageGRID Appliance download site. Thank you again for your suggestions. We appreciate your help.

Kathy

**Closed by netapp-madkat** 2022-05-17 20:41 UTC
Labels: documentation
